site_name: Proxima
site_description: Cuore dell'Impero
site_url: https://akeera98.github.io/CampagnaAvventurieri2/

theme:
  name: material
  language: it
  palette:
    - scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Passa alla modalità chiara
    - scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-night
        name: Passa alla modalità scura

nav:
  - Home: index.md
  - Lore:
      - L'Impero di Proxima: lore/impero.md
      - Pantheon: lore/pantheon.md
  - Storia:
      - La Piaga del Fuoco: storia/piaga-del-fuoco.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
